### ISSUE TITLE
Is it possible to setup a Windows Bakeware release in GitHub Actions?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [bake-bake-bake/bakeware#127]
Background
---------
I am trying to get a Github Action working with Windows and Bakeware because I am trying to create a release using it.

However, no matter what I do, it seems the environment variables are not being set.

Code
-----

In Bakeware’s setup page it is mentioned that we have to set the MAKE and CC environment variables. In Github Actions terms this means:

```
env: 
        CC: gcc
        MAKE: make
```

However, for some reason, this is not working. Here is a Minimal Working Example of the code that replicates the issue:   

```
name: build

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on Windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.x' # Define the elixir version [required]
        otp-version: '24.2.x' # Define the OTP version [required]
    
    - name: Install choco
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install bakeware dependencies
      shell: powershell
      run: choco install -y zstandard make mingw

    - name: Install Dependencies
      shell: powershell
      run: mix deps.get
      env: 
        CC: gcc
        MAKE: make

    - name: Run credo code analyser
      shell: powershell
      run: mix credo --strict
      env: 
        CC: gcc
        MAKE: make
```

I am following Bakeware's official recommendations to install it, I am using `choco` and `powershell`.
Nothing I do seems to work.

Questions
------

1. Is it possible to have bakeware work for Elixir with a Windows release in Github Actions?
2. Is there a plugin that already does this and that  I am not aware of?

**Comment by simonmcconnell** [comment]
Have you tried using the actions used by this repository?  Personally, I would steer clear of chocolatey and use scoop because packages actually get maintained on scoop.

https://github.com/bake-bake-bake/bakeware/blob/main/.github/workflows/main.yml

**Comment by Fl4m3Ph03n1x** [comment]
I am not a fan of chocolatey personally either, but in your install guide you do mention it to install the dependencies that bakeware depends on:

- https://github.com/bake-bake-bake/bakeware#building-on-windows

In your github actions file, I don't this step. Why so? Don't I also need it?

I have updated my file to use `cmd` now, here is a Minial Working Example:

```
name: build

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on Windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.x' # Define the elixir version [required]
        otp-version: '24.2.x' # Define the OTP version [required]
    
    - name: Install choco
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install bakeware dependencies
      shell: powershell
      run: choco install -y zstandard make

    - name: Install Dependencies
      shell: cmd
      run: mix deps.get
      env: 
        CC: C:\ProgramData\Chocolatey\bin\gcc.exe
        MAKE: C:\ProgramData\Chocolatey\bin\make.exe

    - name: Compile everything
      shell: cmd
      run: |
        mix deps.compile --all
        mix compile
      env: 
        CC: C:\ProgramData\Chocolatey\bin\gcc.exe
        MAKE: C:\ProgramData\Chocolatey\bin\make.exe
    
    - name: Run credo code analyser
      shell: cmd
      run: mix credo --strict
      env: 
        CC: C:\ProgramData\Chocolatey\bin\gcc.exe
        MAKE: C:\ProgramData\Chocolatey\bin\make.exe
```

Which results in the error:

```
==> bakeware
mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj"
mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/launcher"
mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress"
mkdir: cannot create directory 'd:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress': No such file or directory
make: *** [Makefile:70: d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress] Error 1
Error: Process completed with exit code 1.
```

Since I am now using the full path of `make` and `gcc` the issue has evolved into `mkdir` not working (aparently). 

1. Does Bakeware need some sort of special setup?
2. Don't I need to install bakeware's dependencies?

**Comment by simonmcconnell** [comment]
That looks like a Unix `mkdir` error, which would be solved by adding the `-p` switch. I'm not sure why it's running the Unix `mkdir` or running it in a Unix shell.  You could try editing the MakeFile to remove the Windows `mkdir` call.

I don't use bakeware, nor do the authors of the repository, so you're likely going to have to do the hard yards yourself. As I said on the forum, I would start with the GitHub actions from this repository and troubleshoot why `mkdir` is failing (fork this repository and edit the Makefile).

**Comment by Fl4m3Ph03n1x** [comment]
By changing the GitHub Action a little I was able to inspect some behaviour:

```

    - name: Compile everything
      shell: powershell
      run: |
        mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj" 
        mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/launcher"
        mkdir "d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress"
        ls .\_build\test\lib\bakeware\obj\zstd\lib\decompress
        Test-Path -Path "d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress"
        mix deps.compile --all
        mix compile
      env: 
        CC: C:\ProgramData\Chocolatey\bin\gcc.exe
        MAKE: C:\ProgramData\Chocolatey\bin\make.exe
  
```

In this snippet I manually create the needed folders and then I assert on them. The output is as follows:

```
    Directory: D:\a\market_manager\market_manager\_build\test\lib\bakeware


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         2/2/2022  11:06 AM                obj                                                                   
d-----         2/2/2022  11:06 AM                launcher                                                              


    Directory: D:\a\market_manager\market_manager\_build\test\lib\bakeware\obj\zstd\lib


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         2/2/2022  11:06 AM                decompress                                                            
True
```

We can see that:

 - All directories are created
 - `Test-Path` returns `True`, which means that `'d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress'` does exist.

This only makes things more confusing to me as the error has still not changed:

```
mkdir: cannot create directory 'd:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress': No such file or directory
make: *** [Makefile:70: d:/a/market_manager/market_manager/_build/test/lib/bakeware/obj/zstd/lib/decompress] Error 1
could not compile dependency :bakeware, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile bakeware", update it with "mix deps.update bakeware" or clean it with "mix deps.clean bakeware"
** (Mix) Could not compile with "C:\ProgramData\Chocolatey\bin\make.exe" (exit status: 2).
```

I really can't understand the error `no such file of directory` when everything command I used shows beyond reasonable doubt that the folder **does exist**.

Any ideas or suggestions for investigation would be welcome :S

**Comment by Fl4m3Ph03n1x** [comment]
To make it clear, using the exact same github action from bakeware (I removed the macos part which I dont need):

```
- name: Build (Command Prompt)
        run: mix compile --warnings-as-errors
        shell: cmd
        env:
          MAKE: make
          CC: gcc
      - name: Test (Command Prompt)
        run: mix test
        shell: cmd
        env:
          MAKE: make
          CC: gcc
```

Still fails with the same error:

```
==> bakeware
mkdir "d:/a/market_manager/market_manager/_build/dev/lib/bakeware/obj"
mkdir "d:/a/market_manager/market_manager/_build/dev/lib/bakeware/launcher"
mkdir "d:/a/market_manager/market_manager/_build/dev/lib/bakeware/obj/zstd/lib/decompress"
mkdir: cannot create directory 'd:/a/market_manager/market_manager/_build/dev/lib/bakeware/obj/zstd/lib/decompress': No such file or directory
mingw32-make: *** [Makefile:70: d:/a/market_manager/market_manager/_build/dev/lib/bakeware/obj/zstd/lib/decompress] Error 1
could not compile dependency :bakeware, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile bakeware", update it with "mix deps.update bakeware" or clean it with "mix deps.clean bakeware"
** (Mix) Could not compile with "make" (exit status: 2).
```

I wonder if I need some special configuration for my Github Workers that maybe I am not aware of?
